export { default as Home } from './Home/Home'
export { default as Catalog } from './Catalog/Catalog'
export { default as FileNotFoundPage } from './Page_404/Page_404'
export { default as Login } from './Auth/Login'
export { default as Registerpage } from  './Auth/Register'
export { default as UsersList } from './Users/UserList'
export { default as User } from './Users/User'
export {default as EditUser } from './Users/EditUser'
export { default as NewUserForm } from './Users/NewUserForm'